import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
orders=pd.read_csv("data/olist_orders_dataset.csv")
order_items=pd.read_csv("data/olist_order_items_dataset.csv")
customers=pd.read_csv("data/olist_customers_dataset.csv")
product=pd.read_csv("data/olist_products_dataset.csv")
##check if the data is loaded correctly
print(orders.head())
print(order_items.head())
print(customers.head())
print(product.head())

# ============================================================
# QUESTION 1: TOP 10 CUSTOMERS BY REVENUE
# ============================================================

# Merge customers with orders
customer_orders = customers.merge(
    orders,
    on="customer_id",
    how="inner"
)

# Merge with order items to get price and freight information
customer_sales = customer_orders.merge(
    order_items,
    on="order_id",
    how="inner"
)

# Calculate total value generated by each order item
customer_sales["order_value"] = (
    customer_sales["price"] + customer_sales["freight_value"]
)

# Calculate total revenue generated by each customer
top_10_customers = (
    customer_sales
    .groupby("customer_unique_id", as_index=False)["order_value"]
    .sum()
    .sort_values("order_value", ascending=False)
    .head(10)
)

# Rename column for professional output
top_10_customers = top_10_customers.rename(
    columns={"order_value": "total_revenue"}
)

print("\nTOP 10 CUSTOMERS BY REVENUE")
print(top_10_customers)


# ============================================================
# QUESTION 2: REVENUE BY CUSTOMER STATE
# ============================================================

# Merge customers with orders
state_orders = customers.merge(
    orders,
    on="customer_id",
    how="inner"
)

# Merge with order items
state_sales = state_orders.merge(
    order_items,
    on="order_id",
    how="inner"
)

# Calculate order value
state_sales["order_value"] = (
    state_sales["price"] + state_sales["freight_value"]
)

# Calculate total revenue for each state
revenue_by_state = (
    state_sales
    .groupby("customer_state", as_index=False)["order_value"]
    .sum()
    .sort_values("order_value", ascending=False)
)

# Rename for professional output
revenue_by_state = revenue_by_state.rename(
    columns={"order_value": "total_revenue"}
)

print("\nREVENUE BY CUSTOMER STATE")
print(revenue_by_state)

# ============================================================
# QUESTION 3: TOP PRODUCT CATEGORIES BY REVENUE
# ============================================================

# Merge order items with product information
product_sales = order_items.merge(
    product,
    on="product_id",
    how="inner"
)

# Calculate revenue
product_sales["order_value"] = (
    product_sales["price"] + product_sales["freight_value"]
)

# Calculate revenue by product category
top_categories = (
    product_sales
    .groupby("product_category_name", as_index=False)["order_value"]
    .sum()
    .sort_values("order_value", ascending=False)
    .head(10)
)

# Rename column for clean output
top_categories = top_categories.rename(
    columns={"order_value": "total_revenue"}
)

print("\nTOP 10 PRODUCT CATEGORIES BY REVENUE")
print(top_categories)

# ============================================================
# QUESTION 4: AVERAGE ORDER VALUE BY CUSTOMER
# ============================================================

# Merge orders with order items
order_sales = orders.merge(
    order_items,
    on="order_id",
    how="inner"
)

# Calculate order item value
order_sales["order_value"] = (
    order_sales["price"] + order_sales["freight_value"]
)

# Calculate total value of each order
order_totals = (
    order_sales
    .groupby(["customer_id", "order_id"], as_index=False)["order_value"]
    .sum()
)

# Calculate average order value for each customer
customer_aov = (
    order_totals
    .groupby("customer_id", as_index=False)["order_value"]
    .mean()
    .sort_values("order_value", ascending=False)
)

# Rename for professional output
customer_aov = customer_aov.rename(
    columns={"order_value": "average_order_value"}
)

print("\nAVERAGE ORDER VALUE BY CUSTOMER")
print(customer_aov.head(10))

# ============================================================
# QUESTION 5: YEARLY REVENUE TREND
# ============================================================

# Merge orders with order items
yearly_sales = orders.merge(
    order_items,
    on="order_id",
    how="inner"
)

# Convert purchase timestamp to datetime
yearly_sales["order_purchase_timestamp"] = pd.to_datetime(
    yearly_sales["order_purchase_timestamp"]
)

# Extract year
yearly_sales["year"] = yearly_sales["order_purchase_timestamp"].dt.year

# Calculate order value
yearly_sales["order_value"] = (
    yearly_sales["price"] + yearly_sales["freight_value"]
)

# Calculate total revenue by year
yearly_revenue = (
    yearly_sales
    .groupby("year", as_index=False)["order_value"]
    .sum()
    .rename(columns={"order_value": "total_revenue"})
)

print("\nYEARLY REVENUE TREND")
print(yearly_revenue)

# ============================================================
# QUESTION 6: MOST ORDERED PRODUCT CATEGORIES
# ============================================================

# Merge order items with product information
category_orders = order_items.merge(
    product,
    on="product_id",
    how="inner"
)

# Count unique orders for each product category
top_ordered_categories = (
    category_orders
    .groupby("product_category_name", as_index=False)["order_id"]
    .nunique()
    .rename(columns={"order_id": "total_orders"})
    .sort_values("total_orders", ascending=False)
    .head(10)
)

print("\nTOP 10 MOST ORDERED PRODUCT CATEGORIES")
print(top_ordered_categories)
# ============================================================
# QUESTION 7: AVERAGE REVENUE PER ORDER
# ============================================================

# Calculate order value
order_items["order_value"] = (
    order_items["price"] + order_items["freight_value"]
)

# Calculate total revenue for each order
revenue_per_order = (
    order_items
    .groupby("order_id", as_index=False)["order_value"]
    .sum()
)

# Calculate average revenue per order
average_revenue_per_order = revenue_per_order["order_value"].mean()

print("\nAVERAGE REVENUE PER ORDER")
print(f"R$ {average_revenue_per_order:,.2f}")

# ============================================================
# QUESTION 8: CUSTOMER LIFETIME VALUE (CLV)
# ============================================================

# Merge customers with orders
clv_data = customers.merge(
    orders,
    on="customer_id",
    how="inner"
)

# Merge with order items
clv_data = clv_data.merge(
    order_items,
    on="order_id",
    how="inner"
)

# Calculate revenue
clv_data["order_value"] = (
    clv_data["price"] + clv_data["freight_value"]
)

# Calculate lifetime value for each unique customer
customer_clv = (
    clv_data
    .groupby("customer_unique_id", as_index=False)["order_value"]
    .sum()
    .rename(columns={"order_value": "customer_lifetime_value"})
    .sort_values("customer_lifetime_value", ascending=False)
)

print("\nTOP 10 CUSTOMERS BY LIFETIME VALUE")
print(customer_clv.head(10))

# ============================================================
# QUESTION 9: RFM CUSTOMER ANALYSIS
# ============================================================

# Merge customers, orders and order items
rfm_data = (
    customers
    .merge(orders, on="customer_id", how="inner")
    .merge(order_items, on="order_id", how="inner")
)

# Convert order date to datetime
rfm_data["order_purchase_timestamp"] = pd.to_datetime(
    rfm_data["order_purchase_timestamp"]
)

# Calculate order value
rfm_data["order_value"] = (
    rfm_data["price"] + rfm_data["freight_value"]
)

# Calculate RFM metrics for every customer
rfm = (
    rfm_data
    .groupby("customer_unique_id", as_index=False)
    .agg(
        last_purchase=("order_purchase_timestamp", "max"),
        frequency=("order_id", "nunique"),
        monetary=("order_value", "sum")
    )
)

# Reference date = one day after the latest purchase
reference_date = rfm_data["order_purchase_timestamp"].max() + pd.Timedelta(days=1)

# Calculate Recency in days
rfm["recency"] = (
    reference_date - rfm["last_purchase"]
).dt.days

# Arrange final columns
rfm = rfm[
    [
        "customer_unique_id",
        "recency",
        "frequency",
        "monetary"
    ]
]

# Show highest-value customers
rfm = rfm.sort_values(
    "monetary",
    ascending=False
)

print("\nRFM CUSTOMER ANALYSIS")
print(rfm.head(10))

# Save RFM data for ML model training
rfm.to_csv("data/customer_rmf_data.csv", index=False)
print("RMF data saved successfully!")

# ============================================================
# QUESTION 10: RFM CUSTOMER SEGMENTATION
# ============================================================

# Recency: lower value = better customer
rfm["R_score"] = pd.qcut(
    rfm["recency"].rank(method="first"),
    4,
    labels=[4, 3, 2, 1]
)

# Frequency: higher value = better customer
rfm["F_score"] = pd.qcut(
    rfm["frequency"].rank(method="first"),
    4,
    labels=[1, 2, 3, 4]
)

# Monetary: higher value = better customer
rfm["M_score"] = pd.qcut(
    rfm["monetary"].rank(method="first"),
    4,
    labels=[1, 2, 3, 4]
)

# Convert scores to integers
rfm["R_score"] = rfm["R_score"].astype(int)
rfm["F_score"] = rfm["F_score"].astype(int)
rfm["M_score"] = rfm["M_score"].astype(int)

# Overall RFM score
rfm["RFM_score"] = (
    rfm["R_score"] +
    rfm["F_score"] +
    rfm["M_score"]
)

# Create customer segments
rfm["customer_segment"] = pd.cut(
    rfm["RFM_score"],
    bins=[0, 5, 8, 10, 12],
    labels=[
        "Low Value",
        "Potential",
        "Loyal",
        "High Value"
    ]
)

print("\nCUSTOMER SEGMENTATION")
print(
    rfm[
        [
            "customer_unique_id",
            "recency",
            "frequency",
            "monetary",
            "RFM_score",
            "customer_segment"
        ]
    ].head(10)
)

print("\nCUSTOMERS BY SEGMENT")
print(rfm["customer_segment"].value_counts())

# ============================================================
# QUESTION 11: MONTHLY REVENUE TREND
# ============================================================

# Merge orders with order items
monthly_sales = orders.merge(
    order_items,
    on="order_id",
    how="inner"
)

# Convert purchase date to datetime
monthly_sales["order_purchase_timestamp"] = pd.to_datetime(
    monthly_sales["order_purchase_timestamp"]
)

# Calculate revenue
monthly_sales["order_value"] = (
    monthly_sales["price"] + monthly_sales["freight_value"]
)

# Calculate monthly revenue
monthly_revenue = (
    monthly_sales
    .resample(
        "MS",
        on="order_purchase_timestamp"
    )["order_value"]
    .sum()
    .reset_index()
    .rename(columns={"order_value": "total_revenue"})
)

print("\nMONTHLY REVENUE TREND")
print(monthly_revenue)
# ============================================================
# QUESTION 12: TOP 10 CUSTOMER CITIES BY REVENUE
# ============================================================

# Merge customers with orders
city_sales = customers.merge(
    orders,
    on="customer_id",
    how="inner"
)

# Merge with order items
city_sales = city_sales.merge(
    order_items,
    on="order_id",
    how="inner"
)

# Calculate order value
city_sales["order_value"] = (
    city_sales["price"] + city_sales["freight_value"]
)

# Calculate revenue by city
top_cities = (
    city_sales
    .groupby("customer_city", as_index=False)["order_value"]
    .sum()
    .rename(columns={"order_value": "total_revenue"})
    .sort_values("total_revenue", ascending=False)
    .head(10)
)

print("\nTOP 10 CUSTOMER CITIES BY REVENUE")
print(top_cities)

# ============================================================
# QUESTION 13: TOP 10 CUSTOMERS BY NUMBER OF ORDERS
# ============================================================

# Merge customers with orders
customer_orders = customers.merge(
    orders,
    on="customer_id",
    how="inner"
)

# Count unique orders for each unique customer
top_customers_by_orders = (
    customer_orders
    .groupby("customer_unique_id", as_index=False)["order_id"]
    .nunique()
    .rename(columns={"order_id": "total_orders"})
    .sort_values("total_orders", ascending=False)
    .head(10)
)

print("\nTOP 10 CUSTOMERS BY NUMBER OF ORDERS")
print(top_customers_by_orders)

# ============================================================
# QUESTION 14: CUSTOMER DISTRIBUTION BY STATE
# ============================================================

customer_distribution = (
    customers
    .groupby("customer_state", as_index=False)["customer_unique_id"]
    .nunique()
    .rename(columns={"customer_unique_id": "total_customers"})
    .sort_values("total_customers", ascending=False)
)

print("\nCUSTOMER DISTRIBUTION BY STATE")
print(customer_distribution.head(10))

# ============================================================
# QUESTION 15: REPEAT VS ONE-TIME CUSTOMERS
# ============================================================

# Merge customers with orders
repeat_data = customers.merge(
    orders,
    on="customer_id",
    how="inner"
)

# Count unique orders placed by each customer
customer_order_count = (
    repeat_data
    .groupby("customer_unique_id", as_index=False)["order_id"]
    .nunique()
    .rename(columns={"order_id": "total_orders"})
)

# Classify customers
customer_order_count["customer_type"] = np.where(
    customer_order_count["total_orders"] > 1,
    "Repeat Customer",
    "One-Time Customer"
)

# Count customers in each group
customer_type_summary = (
    customer_order_count["customer_type"]
    .value_counts()
    .reset_index()
)

customer_type_summary.columns = [
    "customer_type",
    "total_customers"
]

print("\nREPEAT VS ONE-TIME CUSTOMERS")
print(customer_type_summary)

# ============================================================
# QUESTION 16: REPEAT CUSTOMER RATE
# ============================================================

# Total number of unique customers
total_customers = len(customer_order_count)

# Customers who placed more than one order
repeat_customers = (
    customer_order_count["total_orders"] > 1
).sum()

# Calculate repeat customer rate
repeat_customer_rate = (
    repeat_customers / total_customers
) * 100

print("\nREPEAT CUSTOMER RATE")
print(f"{repeat_customer_rate:.2f}%")

# ============================================================
# QUESTION 17: REVENUE CONTRIBUTION BY CUSTOMER SEGMENT
# ============================================================

# Calculate total revenue generated by each customer segment
segment_revenue = (
    rfm
    .groupby("customer_segment", observed=True, as_index=False)["monetary"]
    .sum()
    .rename(columns={"monetary": "total_revenue"})
)

# Calculate overall revenue
total_revenue = segment_revenue["total_revenue"].sum()

# Calculate percentage contribution
segment_revenue["revenue_percentage"] = (
    segment_revenue["total_revenue"] / total_revenue
) * 100

# Sort highest revenue segment first
segment_revenue = segment_revenue.sort_values(
    "total_revenue",
    ascending=False
)

print("\nREVENUE CONTRIBUTION BY CUSTOMER SEGMENT")
print(segment_revenue)

# ============================================================
# QUESTION 18: AVERAGE FREIGHT COST BY STATE
# ============================================================

# Merge customers with orders
freight_data = customers.merge(
    orders,
    on="customer_id",
    how="inner"
)

# Merge with order items
freight_data = freight_data.merge(
    order_items,
    on="order_id",
    how="inner"
)

# Calculate average freight cost by state
freight_by_state = (
    freight_data
    .groupby("customer_state", as_index=False)["freight_value"]
    .mean()
    .rename(columns={"freight_value": "average_freight_cost"})
    .sort_values("average_freight_cost", ascending=False)
)

print("\nAVERAGE FREIGHT COST BY STATE")
print(freight_by_state.head(10))

# ============================================================
# QUESTION 19: MONTHLY ORDER GROWTH
# ============================================================

# Convert order date to datetime
orders["order_purchase_timestamp"] = pd.to_datetime(
    orders["order_purchase_timestamp"]
)

# Create year-month column
orders["year_month"] = (
    orders["order_purchase_timestamp"]
    .dt.to_period("M")
)

# Count unique orders each month
monthly_orders = (
    orders
    .groupby("year_month", as_index=False)["order_id"]
    .nunique()
    .rename(columns={"order_id": "total_orders"})
)

# Calculate month-over-month growth percentage
monthly_orders["growth_percentage"] = (
    monthly_orders["total_orders"]
    .pct_change() * 100
)

print("\nMONTHLY ORDER GROWTH")
print(monthly_orders)

# ============================================================
# QUESTION 20: EXPORT FINAL BUSINESS RESULTS
# ============================================================

# Export important analysis results
top_10_customers.to_csv(
    "output/top_10_customers_by_revenue.csv",
    index=False
)

top_categories.to_csv(
    "output/top_product_categories.csv",
    index=False
)

monthly_revenue.to_csv(
    "output/monthly_revenue.csv",
    index=False
)

customer_clv.to_csv(
    "output/customer_lifetime_value.csv",
    index=False
)

rfm.to_csv(
    "output/rfm_customer_segmentation.csv",
    index=False
)

print("\nFINAL RESULTS EXPORTED SUCCESSFULLY")